apiVersion: v1
kind: Secret
metadata:
  name: vikunja
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:iaEGNDqPEQ==,iv:uZOSI9IHoa22Z717FcJBYHzDycKTy7RLIbKq6tnL5e0=,tag:un18g86kcsnjMLSipS1DcQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Tu/yGz4aP4ob3SKTgRc7McxPKvv33IRhWoYcUMrT+iXjL/Xq6UE=,iv:gqr52aG6XqqZ8p1aMOEtUJjfBu4XZcLma+FwToArNj4=,tag:COlXeKhBNcDqDdIbBDlNzw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:KyyDkzfhTQ==,iv:QXQt4nBOmm1OCNkVCAViUY8+d0rfVgLzvFTC0b1+5YQ=,tag:bhF/V9sm2zdfLOQv+eCaaA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:YyEsJrSZnU8tAsIqJhjM+L5+JT3LooFpzN1/jbSiGcQ=,iv:1O1rNOZc7WTOAUHVdELuWJjXdnBVGxErNxDjJ6WsOqQ=,tag:qS5J5YaJvo1SfQSxFGDMJg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:8vhINZEh0x4=,iv:epLkMGsTGPe9jYnyWiMAKXpAdwPCe/58mYnaV9tcQxc=,tag:XSF9rXAUtyQvcokqbUYi8A==,type:str]
  VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:+p6rsFNYsQ==,iv:6zITDaHTDAE/eCwMDuAzSXHj+8trNEaRI4CckKkQO/Y=,tag:K+LFwpoGZQsORWoIv+ztFQ==,type:str]
  VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:5I53MjDvWSD5ws2Q8jpzZASJMgcTOw9qcuwzvajKFKbJNWeUjMM=,iv:sYRidF13dOkqNZT6fjlK4L7+2WqpRavQ0koz+bjQGSI=,tag:48jnRxLkLsO1dh+bgwmdaA==,type:str]
  VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:ucBNj4KnVQ==,iv:lj+U+XSoh3NUKexn3uIqXzFaEvJqOwtfzWltf4rBAdM=,tag:M1kYpcbPzrJ23RkgCFOPHw==,type:str]
  VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:oiDmOJD3Bekqvp4cbAdcndHX/qBHmTnOFttBSsz3ur4=,iv:cIxbbb8/p7MNn9gb1P1Fn3ONxuGE/MCGpeM0ZWSZNYo=,tag:VpliaEBiomgl43f6VM+cpg==,type:str]
  VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:g1kGEak4WODdmHj7N8GxxE17MQpPsiXFUH58ftjBWpQpfhhiXRHC/YdqgSzePeB5bZkus/dYWCbRCme3rSLoMHTHrs+c2HYCEwmi7uj3zWMBsYH35H+Pug==,iv:lxxJ43M6Wk47xJwRC1XngO6AaGhdMAa6kCPONDpPgow=,tag:jiv4XSPddAr9M4gPvej6mA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc3FIVVpwdlEza05kVFFk
        UkdrbGNLQXZua1NWYXozR2wzcGZsczQ3ODI4ClY4b21qWG5tZnhsU1N6Mld0dkM5
        eng3M1pkQ1lTU2taVnRmbFZwZkc1M2cKLS0tIGd6aHBwemlaQjU4RXhBZjhvMXRX
        bytmV0ZpdGR5UWtHbGw5Zm9hREdKbk0KbjdTz8l9SM1PuJE36n0lhXcPxzSTcV5P
        M6XeegteZV0TO67BBfXvSiHwViZLr0gPODa2R7R8Vi1sl+JQOJgPPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-05T05:41:37Z"
  mac: ENC[AES256_GCM,data:rvRGG4A6StSITfna6JViKDijqXQdSZIK/IDn8GQclT2yXTmNaScpxxpate8D+muDsuPD7hgKFYrFOzxi9wgjWOq3F9dyosz1YcCk8loM1Yx82nIyumTsiQ7aVeDCgCndpVDgnyaafvWYOlv73WNtLcms5oRWVxQaoiF2YVS0w2I=,iv:7avKJLgdzQ7DEX5CkonJ6s0NcUVvyg6ipm9YDzIpzb8=,tag:QMJpdTD6ipWuSN0FngmrMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
