# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cross-seed
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      cross-seed:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 6.13.7@sha256:93418ffe42ccda770706b10294b46f8642bd1f6da4ca57b4c11b1b220f54e3d3
            args: ["daemon"]
            env:
              TZ: Europe/Oslo
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 2468
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 993
        runAsGroup: 995
        fsGroup: 995
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: cross-seed
        globalMounts:
          - path: /config
      config-file:
        type: secret
        name: cross-seed-secret
        advancedMounts:
          cross-seed:
            app:
              - path: /config/config.js
                subPath: config.js
      torrents:
        type: nfs
        server: 192.168.1.10
        path: /mnt/wolf/torrents
        globalMounts:
          - path: /mnt/wolf/torrents
      tmp:
        type: emptyDir
