# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goboden-kratos
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      goboden-kratos:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/oryd/kratos
              tag: v1.2.0
            envFrom:
              - secretRef:
                  name: goboden-kratos-secret
            command: [/bin/sh]
            args:
              - -ec
              - |
                kratos migrate sql -e --yes -c /etc/config/kratos/kratos.yml
                exec kratos serve -c /etc/config/kratos/kratos.yml --watch-courier
            ports:
              - name: public
                containerPort: 4433
              - name: admin
                containerPort: 4434
            probes:
              readiness:
                custom: true
                spec:
                  httpGet:
                    path: /admin/health/ready
                    port: admin
                  initialDelaySeconds: 5
                  periodSeconds: 10
              liveness:
                custom: true
                spec:
                  httpGet:
                    path: /admin/health/alive
                    port: admin
                  initialDelaySeconds: 5
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        ports:
          public:
            port: 4433
          admin:
            port: 4434
    persistence:
      config:
        type: configMap
        name: goboden-kratos-config
        advancedMounts:
          goboden-kratos:
            app:
              - path: /etc/config/kratos/kratos.yml
                subPath: kratos.yml
              - path: /etc/config/kratos/identity.schema.json
                subPath: identity.schema.json
    route:
      app:
        hostnames: ["auth.goboden.no"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-goboden-wildcard
        rules:
          - backendRefs:
              - identifier: app
                port: 4433
