apiVersion: v1
kind: Secret
metadata:
  name: goboden-kratos-secret
type: Opaque
stringData:
  DSN: ENC[AES256_GCM,data:ecM6LCBtZmlEcnHwocLy7pYmQ9nMoAD7mqG2V5BocrmeDF/WAhMnrRqu8yM1inZxetiDSGnycg6HwhsgZQLoZcWHhCyF+Too/h+f/cUdzl0QheS17ns=,iv:rC0lCEEle6wcBWGJkAX3QtGDTW2cJfiax+SCAChq2aA=,tag:ApD6AEko23XdKZ1Z6EHkpg==,type:str]
  SECRETS_COOKIE: ENC[AES256_GCM,data:crivSqKs/x7CpMSL4gdMt3MuZIANjYkM8Lxnxhu3pU6PN25cDPaiWRb0w2A=,iv:1riNtrlXDW0Y+eY+kOdEOu5X1HzO2ibUoY0Y4MkEE9Q=,tag:1DgAbphZcuFf4QFVp4qsuw==,type:str]
  SECRETS_CIPHER: ENC[AES256_GCM,data:VyDwKM45Cm0cEWnljIvrWi8ALpm7AwKYmcCbisV+pxDlJvdQ2klw0BdUQ58=,iv:ct5Du7EfzzIFxInztlumVGJr8gEcPKbHb6D/t1OZrT8=,tag:ehwaQxcN4bSELDC7LSIwmw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VVFOb3hSOXBtM2Q5Nlph
        MlBnZlhubzZLazg0VFJNd2ZSSU1OWkJMc0dJCldpaUhZUysyWHhTYlI3WmpQUzFN
        dm9vVVRyYURadDJ2ZldRbkF6R1RTOGcKLS0tIFdrL1JseUswdkJNdmNCSW9SZXho
        TXNLY1djb0NuOUplVndYVlN3c2dzQU0KJASzwyFx0WSafKnba7LBnJrzXgEDILYv
        M0RtI0KYVSOSllM4lBnaYc0MejBP/cPyfeZe81FVfbsbjHa9wjIuxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T10:24:02Z"
  mac: ENC[AES256_GCM,data:vOXEOpI9SQlDT8dzxX8E01uLvrFDUEyZSSYLuVwmyMS4Jc3L/2w3QS4bMHMX/v7hzzssxujROFmOjFABKK5u51AiUyFEdcwn+5xVxAsdn0WkHLhSMCDMvAjLSId/vcnw3UluoCVdpYjSwCq48Vd9m5luPfbYM+rU64Qftuzwr/s=,iv:jKTmWy9mBQuvz85dHyjtzIRErCLiuhnorlKkLpUpS80=,tag:N2tlnGJlsFkTHsWB0FxhGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
