apiVersion: v1
kind: Secret
metadata:
  name: goboden-kratos-secret
type: Opaque
stringData:
  DSN: ENC[AES256_GCM,data:dZrEaDFhm2R7OyOgKFZZrNp1rUDIYKXdNwnf58ITA92LU5i0dAuePJP8dCHYuRDbvn82IHeKV5bYJSxZOrf2pU9gVB3+7tw+J8JS/N8pqinLtfvf84E=,iv:BSAEmEcSABYXh/CRENCoshIuimU1NFKSgK/mTs5bdYo=,tag:m0b6BWxdJcmnE/dIY7Q3eA==,type:str]
  SECRETS_COOKIE: ENC[AES256_GCM,data:zVwijxM9zaWUMSSuagNL+nYRl80dBXU0mC8ht/rFLX2K9+rT2QK5,iv:zp+i3cYYZcBb/kTcOkDg43pTcovkKFXyzYtPl7gRaJ8=,tag:mrgL6NuhkX+LyTiIA97npw==,type:str]
  SECRETS_CIPHER: ENC[AES256_GCM,data:641PivXzA/0lTLYVIlfEpTVEAywc4c/ZvwK49cGT31keEQdowkJk,iv:UfADax9ZHcWNwvLYUl68BGPBNRkH2e7k7Hvdf9vxrGM=,tag:kWOr1jWye9vGy2E32U0now==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZUdvbXV6b2d1TTdaOHBY
        SlFLT0s1ZWM5blZlWktwSkNtTGRzNDdTcUhFCkcwUTZSa292TkRaeFhKMUkyMWI4
        SUc0OTJNaWEwcWNHYWRnZy9rRGdlWXcKLS0tIDNUOW5zQUVOUytjUEpXdkFPMHNl
        cE5IRW1yTGZqSjQ0Vlk0WXUvZ2NSczgKLAXm4KO6gUeYmDwRiW0gWSXPer/1RlHH
        aDBFzHiOiMtptbnDjO8RNnToDKu9E7CUF/HJ2if8E6gJmTm7tWq6zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T09:32:45Z"
  mac: ENC[AES256_GCM,data:jeJi5cmBrr379KOi3xEKC8BozFlOhORg16YsQX82YHjcbQzB2aTKKckbUbUFoWrAB+SZPkgz6akJkOKlS/jvaf8iJD5k0KdJYYLkC7SySF4G5sRte/YTdXHQMHonpaQg8LTQioyfF2TVMDXTeldiTGELSdwol0qM0AOveobH3JY=,iv:LjHTxoOEkzrN5ZdQkjVh0rEt3w5cnHVlmbCM66NbnPw=,tag:+Qyl9NNNhiQoQhxilq2j1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
