apiVersion: v1
kind: Secret
metadata:
  name: goboden-kratos-secret
type: Opaque
stringData:
  DSN: ENC[AES256_GCM,data:AY2CipQGwxGQWlEdXS3as/kFtyYP7v1l2sc44nMDTNnYLrz3V9NLAT8soyJqiCTWj5mjwBXKtLj2njzpzBUDcd+zuUa8Ks7vF3pa9Oa1OZzIX3ooeVA=,iv:19QXKG5mSmkLTykNGjCpF/W2CsXFfR9TPmoXYh7Z/es=,tag:N6YFS5N9PfSm3cs0mTkDBA==,type:str]
  SECRETS_COOKIE: ENC[AES256_GCM,data:5i36ppIIeA893TocuKhLOoqIH9kNd1iGJVuc0T/4AHg=,iv:6IUU7PevgBbeJx6DsYIwFwpiOGE0Lvn0DQY8BgSwCx4=,tag:QzaRRRenlw80LFOuu3AnsA==,type:str]
  SECRETS_CIPHER: ENC[AES256_GCM,data:55CIRRbdfV9Kv8X9+C+oL/BMhXrxl0daXVdGf4H0SUc=,iv:lUSoqXhguXZNKiXrXI7NZGSrrHxAcHtfEd5a7zq4prE=,tag:P6EAMRsWu6pfiOlKQbZUMA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSUx2Y2wwbHpCOHE1TGlB
        Z0FUUnRLNVhVRTVnMkFDaDNSbWdaRUlBb1VFCk16SUUwZG9EbEU4ODZqN1R4ZFpE
        N05JamIwZGxGQnIvaytxM2o1bmZJR00KLS0tIDRFdVRKYi9DMHNKVEZ0cm9zVXgr
        aUFyL241RTRhVXY4YlE1NnA4QzBraHcKFfJCwDud+vEdDMSLMqMokUDUAF61K3Jq
        hM+9M///4/N37FJY5oxCQNrtJo644UFHiv7I32Dwrn2i3nZBZ3lnFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T10:34:10Z"
  mac: ENC[AES256_GCM,data:D1+22XluSEshfZkSnTK1oUWUhRi8smMknpsMkmfuBa1H4/IP3AL8//dnKxAX62Wm1fWQAVRl50ccsVfiIyWifsrQK7P5QqwbWEY4bzrIHboL1t+HvmKVudeE7vjQ03E3ILmDVxoZq1+v4akTHR0jfJ7iskgawMDxkZpSySJjgmI=,iv:ZB+h3RYCVezQmVusvpHQThXglTn3xjK3xmCXbWFHg7s=,tag:Ce7hVrWANIDL+1hrG+t/YA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
