apiVersion: v1
kind: Secret
metadata:
  name: makkapakka-secret
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:0uomtVCq38b7Go3uP0alhl4Ds20cFF47UC9wjTeqx5PbungLYwxF//cTF0hddVyUiZYkZGY5Eyr7p1OXU51Blg==,iv:IkQqyBVGDX8qjLZbjxGg7MPyN7ClgFOE8SAYYA1A9H0=,tag:8DUGdU821m71IvkGQRo+6w==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbE9Scm5ZTVMrYjgvUHNE
        ZUlaL1o2RC9zVXZRN2VKdFpFQzFIWk1VbFdFCmFUVmc5SDdPcytybWxDa3NPaThR
        MHE2dmQxSjVKeHZ0NU1JTUdPWGtXdEEKLS0tIHYxNE51d21zMUwyOEtWbWZjSVdv
        SkFWZWluRHhsL1J0SWJaRGc1MTcxbmcKohknZZq8lINSjoXe1GteL8RYvmuNj4Wk
        38Qh2QxxKwFSUXg3/n98IiS97dbwdM0/fomReZv57ACpAScfv0jNmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T17:41:42Z"
  mac: ENC[AES256_GCM,data:qltojAw9PNosMiwETykEHBnOJC+mySyRxDPm9fFdfCmShGLI8jUC6LC4Y1S2cIzf3T9VS6Id/adtZdz3iOW1MhgwtvXNCeRQa7S/FHejVukYdLb3rsxCIOtG08f07I+iiMoPI0bXJXmyYtpswJt/cEdsEd3tR2tpWtfGrenSZL4=,iv:PWwE3CWjjsrKIftjdQQ2b6O0op/7BaqjM0Chk5xExQ4=,tag:BIaQS74pTFfJYieXjKiiXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
