apiVersion: v1
kind: Secret
metadata:
  name: makkapakka-secret
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:TDlqLRc1+8YqrJih7/7rBZbpGCCzn5lRgUO3vScRVuV5xRJri8rrgqBGuVWly+p2C4n+Ee7MctrxmdK7BJYBHQ==,iv:NhpZBcWLWDngsxBk8e+RzoXdewScMTknD1hdDiNLybM=,tag:KBFN7RiZK9nB2lGfEIdbDw==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:CQF77A==,iv:30RSWy5hZUZYhNURrEnxGk8Bh73h9NM21NsN0I6VPi0=,tag:/PxU7sXb6RZw5ZnIiyBM/Q==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:9mq6MoKxmYlLPDY8QJxBnYqHcVcX1SaIQvwZR/K1Od6st3uq1XU7ZQw+GuXrzi0oOb8C5UdGQUr50zNGO8psyQ==,iv:z8GhHEpOe5YpkOxqBG1/GIp6HP0yNVZUoxLSwOR0BGo=,tag:Ke8ryqHSfJtdVKidHB3FSQ==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRjZJSTVnd2xwdDZiZmtZ
        c1lvb1AyazNXeDNBRS9BY0VDVDVhREw5eHljCjcxbVMzMlk5M1pHSDBaNnlIbjNu
        eWYyamdIdHBVcWYxRTBuUXJkYmcwd3cKLS0tIFR6cTM0NHg4UjR1WXVHcnVkdmEv
        VnlCMHNnRUlGczlJSFg2MXF2SXBzakUKg58P3KKdTyfFwIpYXKUdqmo9RMzQOO7B
        +gk5E3hLdFApKFIRaNorodRkZzAdVL9OX4+n4Opbc6kTcSMWeJFEeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-04T20:40:20Z"
  mac: ENC[AES256_GCM,data:ZbygmGONCBFmmlFMkdz5jofIH4qi/YlCVoyWIeKDtvSowbMBimEqlIW6jHwbL315bn9KFs/OBKfaCv9UtfM8DBdBspLLPQD4Xmuc1PbapxHgiACb3WoxcQ5fgVDSzgPvJmjbySCS3gnm1wPsY72OYU+2lOlgcCoNGtIeh7bVqtU=,iv:NwhHhD/yAIF1cUN+WKtZJFO9D+7npecpPetCzJKCOsQ=,tag:vf4R70INj2Ltr1DBCC921w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
