apiVersion: v1
kind: Secret
metadata:
  name: ha-mcp-secret
stringData:
  HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:GTx1oe1lF8J+0Q6oN1hn+g0In6tK6dPB6ZIV4pCf4Exv0pZvAWEogGkqAB9/iGpvFxmoA80LAo04SDrPaQcP9L587O3VgLt6GzsmIP0FUdulY5kJA+FegB6n+QFrphdw6BjOQe5mUBl6oDrMxbESfDsTmVAYwBTgUnBE+8lBSACzevOESAFBj88zxHcMt/z4TSPrAHZmeQT/zSY74voBumUyO8/4PnOFccsjW+7pf4vIj9LRnaSS,iv:fvs9KbQHLE8geYOrH8/+LNkbTm2eTGI68EEEF+fOMzM=,tag:EdvepXsxF91wL/GoyhqAVA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTmZ2S1N1UElDeHd0WUlB
        YkRhNjFKTDZ5cE41TFg4Y1A5Rk1RbE9LOUhVCk5GQjR1TGN1bW5TRElTSnlaOUpV
        dTZRd05VWUVXWkEyNnlmUDhHYkYwNWMKLS0tIG9Pak44K3RIWWFqZU5Nb2N2ZmQ5
        U0VxVisyTjZNRGg4ZGkyZmV4Mk5KWHMKugYdM+ABIYbyI1Z1O3C9efemD5bmUch1
        R4hNk4uARFmPM03d5k27SpeYkfqHlTMcyfaxzpdcNvlTPJpqMiWgzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-17T20:17:24Z"
  mac: ENC[AES256_GCM,data:sk50LPLg5Z3qiGubxffgtdXmaWcjSsP12mfY7syXiIcY0aokcW/eeQY3StSa/qFrg5lANN/lGqLRWFvsK1R/2V7Lj/hgbJI3X5ZdvqNDA2hwV9uNGhsw+BYpIuXLLYuTs/c189idrOB3V5DKJGWzBGsq3ClmUoI9jgKu/nSiy+U=,iv:R0VZFvtDWvFK8F39J4DDipDnkqYwC0GbhQhU0WMSYO8=,tag:Nu2tjgHORfj9AR8TfJekCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
