# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app n8n
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      n8n:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
            envFrom: &envFrom
              - secretRef:
                  name: *app
        containers:
          app:
            image:
              repository: ghcr.io/n8n-io/n8n
              tag: 2.15.0@sha256:136640dc074bb9f690674a72b65e02a4054ea305db8a95c8f1892e6d7e43afc4
            env:
              TZ: ${TIMEZONE}
              GENERIC_TIMEZONE: ${TIMEZONE}
              DB_TYPE: postgresdb
              N8N_PROTOCOL: "https"
              N8N_PORT: &port 8080
              N8N_HOST: n8n.${SECRET_DOMAIN}
              N8N_LOG_LEVEL: info
              N8N_LOG_OUTPUT: console
              N8N_TRUST_PROXY: true
              N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
              EXECUTIONS_DATA_PRUNE: true
              EXECUTIONS_DATA_MAX_AGE: 7
              EXECUTIONS_DATA_PRUNE_MAX_COUNT: 50000
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["n8n.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /home/node/.n8n
