apiVersion: v1
kind: Secret
metadata:
  name: n8n
stringData:
  #ENC[AES256_GCM,data:ro4UW0pZbZp1plx8cOVZpnU/YA==,iv:e4/kgUfRJLWDUw1YftPw8cXf7Cg7JuZx5nbIdIgK6/w=,tag:pc3jV1k01HA/UF99t0YqZg==,type:comment]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:6Mu5J4GmTDmVIUIQlzXG2HxznTIA5iEzGn5nqRjS6uJfqNHtby90m0vgD5uuc8GsfQOknDkHXCe0m55D,iv:hrieDfkcr0E/sQmy55dfjvykYuZX2qRhaMZQjlePxXY=,tag:81JIOzFt+IFM5fWaQJ97Qw==,type:str]
  #ENC[AES256_GCM,data:8RosJGM3CaQgBnFp/b/4B+QfSwiIshA2,iv:HarTLbpfRuZfArLbPt0gT9uKGmpjSLzKP/l58+rzLpc=,tag:gzclH6grCnWm/BnqtE4S5g==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Cg7Z,iv:ofgsoJv7Nt5KsAO+hvZPFjUZZt85OiRNdrIgjsZtCPA=,tag:aCAQOgHDiE3CNFzgQ6d7YA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:0k0v+O4AmOLS9EtVQWHrar+uY401WPeHU+snitQMsweJYh59hIc=,iv:MpKAmvnnfPBsLZbTF9ODJfyiN+Qy7Rr3yO/U/Pe6xvs=,tag:8Nk1bPAFS27HB104RiPa/A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:iBf0,iv:y18ihZ0v4+ArW5+bWBY6sArHVEOqsPmWZEDj2VhhQyA=,tag:+t5nNFibASx94+jqsZ8RkQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:peR4oDkS+V/+Jt8CHyFDb19dq52Xx2aW7GPRAyU+suMEllaseXaePoVhMvvedigoUVLJe6COtDCYZwud,iv:Kp5/s1i3APQYane3ZxzkoKj/s+vDmJeKvz9lMEHudkw=,tag:FFTj9US6ylBpsHy9txOBVg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pcg8WBpXJQs=,iv:PCN4e87SO2DBBBHEvztq8XqvM2/+Sasfwo+OV+EY1g4=,tag:nK7KDIaNy/KXyfaLviCk7Q==,type:str]
  #ENC[AES256_GCM,data:qujl0LL4G8K9mYqF1QZHw5TYtrgBKdXH,iv:IScdvHblHHRDk/LkE5O7XcR+Ila9b3Tc2IvQazaUbpY=,tag:IAJ/9cZTfrZ02fDRFuJFGQ==,type:comment]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:MY8ym4ZRlTsTxAZsq/lQT/O9lZqiOoGQBli7nLaiDUxWJ730qp4=,iv:gFYqzZ35U2IeYJCmMXxwHHtDDy2ztUjs6aC0RTRM+2M=,tag:SHptYVub7OInsL/UOPWF+Q==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:gSIN0w==,iv:5ktfkdeG5UNALPcT7KJTOFcwgoKkcC5P84n5N+qpfcs=,tag:rxOTuIQFIsye5wQnDxLxPQ==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:AODQ,iv:/iqURbqlZuZLURUNc+BN1vGZM6AVS+zbgBCWKKZN/jw=,tag:IDUhBSNxu2ASeZ6hIbMhSQ==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:BfJgHl9tKzeB30SzsIm/mcicWPNC0Oik1fvXv6Bl4H10MVzjvTo8DGMu3eoZHfa/Im24Dj7bJ+t8yXLH,iv:kV1tbJLAxEjhny4lzg8Nx95Ms0+TO5CT6qq5/e9pups=,tag:kP9wxjv0xG0mdcBiU8Q+fQ==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:fClR,iv:H07WNtcUOvlFaG2QX6sz/4XyQfK054Xt56qlhy/WsaA=,tag:OTo8hst6h25Oygv3JKEHLw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb2JXaE52dE9CSExQYlRC
        NlNZeWFGYkN5ckFXOG9Qb3BYNjBURmE4TlNVClR2bjlEam1FdkoyZ2hib3h2M0RB
        UlV6Yy9oWmNoYm5yeno1Tlg2bklTTkUKLS0tIHp5NU93WVJnZEZhWm1wTlZsTTJo
        cVcwTFNERE1YZkRBSU0xTXNBNlpld28KiEedn+dvzsg4m8ajCdB2nHrje1z8pqnM
        JtUTVQv7Uy/ldYkkh+1wqR6jXBzQ5L1g2BMXM3aRJYgUzHF2vgIKHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T19:48:28Z"
  mac: ENC[AES256_GCM,data:m8Mev1dFIemOYmAJaE3i3fNMX5JbjelON0Wor4+aP8I1oAqSlI+Qy5ushoXVPqIujeNa0xARoRiSNSsN+7eGMmo8hxMg2Ap9LIpo9o/Oa4b/cVAwa9mDSmY79fwDNfWKluS157I96IQiS8t2uMBkyTmBtgFZ61j6uzKUqA10nig=,iv:BWWNzvpaLlT6guur5xbfygMx3QBJUvz3AVezE4098RY=,tag:2lyyUFm0X8R4bidWqEsVJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
