apiVersion: v1
kind: Secret
metadata:
  name: n8n
stringData:
  # n8n encryption key
  N8N_ENCRYPTION_KEY: "CHANGE_ME"
  # postgres-init variables
  INIT_POSTGRES_DBNAME: "n8n"
  INIT_POSTGRES_HOST: "home-ops-rw.database.svc.cluster.local"
  INIT_POSTGRES_USER: "n8n"
  INIT_POSTGRES_PASS: "CHANGE_ME"
  INIT_POSTGRES_SUPER_PASS: "CHANGE_ME"
  # n8n database connection
  DB_POSTGRESDB_HOST: "home-ops-rw.database.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_PASSWORD: "CHANGE_ME"
  DB_POSTGRESDB_DATABASE: "n8n"
