---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/imageupdateautomation-image-v1beta2.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: goboden-app
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system-automation
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "chore(images): update goboden-app image"
    push:
      branch: main
  update:
    path: ./kubernetes/apps/goboden/goboden-app/app
    strategy: Setters
