apiVersion: v1
kind: Secret
metadata:
  name: flux-image-automation
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:Hg0QFvo=,iv:1sUrnA4pwyv6mlyurcquNV2tgBnIZ7uEebAG5Qpi3cA=,tag:YIBC8o0EYMW9vtMgyo/oxw==,type:str]
  password: ENC[AES256_GCM,data:8LD8LfttLLy6uNefb4VE/USukk7DYVpbI/h351IoEdlJsN4U92wkf6O1x6IURHDOWMdImlizZzEjFofFSLHsaqSkiRr6pk2dgnBtbcHlpg3vHVGuDTgYS7b80VvY,iv:u0QGsKjqntywMdBv57PpbbO9jVDZ1N++UcqQBBPmKbc=,tag:9RfuUXUxbAxS2FzR8vdiIg==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcTFCSmhQMHJzSWFLbFow
        ZXhjOFF1QWdueHRlTmQrWmpveDArbm9MSVZZCnFKY08rV09vVUp0QU5DQlpQdm81
        SEFKelZLckpZU3FIOWRCcTdWMmNGcGsKLS0tIGpSYjZQRk5rNStnYWRwNS8raXFt
        dkIrV0hYTjlacTE5Q2Q0RXQ0ZzRWKzgKss3/8zsmyi9VHlofIAOxWG4Nn9bxQv2o
        juo2VvF7WrRD6ZTjz7zg+gxkyR9n4hHquiyu3sujwb0vdAUTBkT0mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T21:46:07Z"
  mac: ENC[AES256_GCM,data:rbll4pfdAsKB1P2OVwOWxJ35jcYMe228sytlHFCv3g1ay7mZ7jlgMIpZaEU9N4nueFqefRwrDUhcgF5nsl8BnlAiFjdaskbFYLeG9P8VjABrWm7tSvoMSqIhWtw3PPbU2XstWarWIy/mEAKMHDIUgK7hq8cNgR0uQWNUnzu4tSI=,iv:TO2IZXyv48mTfe9xU41clmIW1mcd9f8ezakvyRZYkro=,tag:uBhqHVYXu2bOtzGFziWmhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
