apiVersion: v1
kind: Secret
metadata:
  name: github-mcp-secret
stringData:
  GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:Ojb7/5Jt6p1agFPKY3HH+mkzBZ3s8iMpRrC50yPt41erfOBnwLAaxUi/3cDZ6Z2gtyLY9yY/mAq5oVNU+WuRnmzWCAQnPgj95zyrKYYV2PipSWUV/jx9Qs8r8yvK,iv:d8WwxBd8vaGPx8rtZxhj9nig9lUSJnYyOFqFAi3Xw/8=,tag:0cmrIGd0gKIT0DnVr/9yJg==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Yys4T1BwTldRd3ZWOXJS
        T0EyMnJNejdFdWZaNGNQUksydGNkMUNpYUFRCmNsTzdudFVDQ0ZPTVdnNDNRSnVa
        enNaVEFwV1lvYWFvOTJ6dGJheVNSM0kKLS0tIGN3ZDd6Z3JjWjlZeDlEVGcwRlp5
        eERLWm1GeFk1b2t6WnlBbzV2MlNzeTQK9suR4mgQ3Zao/xkryJMFM0FG6BfDVsjq
        HTKcrR8gzlOTohXXRMuEup9Alchg3YkJNNDBSJjIRqljYEIHyytM/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-03T20:34:09Z"
  mac: ENC[AES256_GCM,data:Ic0LwXvWB0gkfXzLTIBX+W89+kXp1FlJIYqkC4g7NkNMfRkN2Cx2XZDu4P5Zzg8OAr9Nz91JCb5RoBzikrdM7Yt7NU2rQG543bYI77jEf5juQ9deDUgYsIq6eRBRxfxJqo47WLkYp7JoSTXHg46G6jIfYBDGp1Lr31EdPCbgKmk=,iv:JK7efLmPGeYbZBI16QN/jjLsSdinulsTAb48q2fRSoo=,tag:dVekersLHsmf9QuRMIhTAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
