apiVersion: v1
kind: Secret
metadata:
  name: github-mcp-secret
stringData:
  GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:3vmLhYgsk2l/1DMnhN6FB/cZl0WmuXPz4G28VvmggbgSSFa/x5S0Hwk9B2zNOqcpIGYSdO6AJSzjbJsCD4AxJY3ImU/tUxwAqt/2pATKStVPrLeKmAU0qZSPIych,iv:Jq4ePU+FumWWXRt0WsNf5z6vWrBdOZOVPzbNcENdRd0=,tag:IklxvLrxMDKgF7OHmsYLwg==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRnhKc1ZISE5CZmZCeS8w
        VThqSTBxSmVmS2tHeFJvTE92dEtTbFZLYlc4ClQwb3VBN2duanBBeFhsY1RDNFJZ
        R0lJbzdUV1ZINTFFWlVBa2tpeFdkQTgKLS0tIDJTSmtGeks5NGZsa09adXhraVlJ
        V1dqRk1BWUxOMVdrNE1JSUp6UHBUekEKxotlVABw922YTNBFNMJb5on1P7WtVCvd
        fbjLgH87YDLFx3EHKxiU1w29imDa84wQ6Fy4Dxlhcb1C35zrR+j72w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T14:30:46Z"
  mac: ENC[AES256_GCM,data:qij0iJj4K+uehaghX4HoPENfyW/z6F/yLeyho0d34RS5xPTNXXLd1Mse5lbj93bQH2NwmBSqK70Af6d/W/6NYmP1f8ZgROFfdLJw26jWH2VYUDFapj3AafwSlFucvnTZnwLQA0PdK3ksr/cHlocKD8rbs5Lyid96ww22vhqtIQM=,iv:Hafm862Gd0O7Wb65U7Mih646Ubav7faWOtUijyAn1cU=,tag:dU3HiXxPIuoH9DPorUw1pA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
