apiVersion: v1
kind: Secret
metadata:
  name: decompme-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:x0VnYCdg3vbZQrLEcjfjogSxEpGxOPsE6VkAew5YBe5S1p7fzWcmxLWzKRoryevN4EPa7iM3QN+BPOB3VxWIEcwILxTmDKYHW3BuVEUD24DXUf1PtRrZWF0oIGkIP3Fa0y4FxcqcsxD0oMLMFwbJzYKZ5mDmSAblsj/KvZIz4xVeq/3rM2IQ19IkEg==,iv:OCF+LRrK+mKPieDZ80sgZTaeWdHVziLQFcM/OZaSvLc=,tag:vf6jtQJY9/4YXXJWPeAXcw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:toDv9e3lqwg=,iv:gIzv++HoW+UdPGQ3Y+CuXipaQVSB3To9exLstID4HtY=,tag:KpQxzJlCDKI+Jtqh9n0YkA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:9iVwzxSPSew3hl5HmtVRBxq9eX+1fFIY9jXRknmBOJqdNhbLQOI=,iv:mNm33lvwszm8/OPCNaz7OQjP+GvRNT5wma7B/ay0+7w=,tag:jdBZV36HYZWrhlVNn5sfoQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:cLAHfZduUxTGVFzwWv7cVj6umSmLE93I1OZ0BTh3RnAdZl+MgDwDgA9Xuc+MXOk+qB0xNlsI1bNC4rxRLPc4Zg==,iv:cYcSzvThUgMTbCEHpwkIPONEV57NiaJ7jZsCEI03bGE=,tag:hXRkw6xv3vxpyMHV7tt0lw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:FIMa9n/vzZM=,iv:ls6FXku2DEO3TBDbb/hreAimPfpZXHHneGjUPwChT8I=,tag:2Cfn6iqjK2/i8yuAfef8bw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:4uOjoteWeGg=,iv:88msE/8eO41/+Vn7Z6lfA4fL7ipMM+a4+mGJPTmwJH8=,tag:I9PA+/DTD2lAOAWKOSSXgA==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:9aZv+QUs/7LcQry2cug/+E/fn11sGBBi3PXudfi20415b6e6j1ZgO44VvveYew4EGG6atsrzdjIVF0YfDAe5BO0C2U7D6yrF+2USo5aVDsLVKWOuWMr93GM2SuDo05oE,iv:M2cZpTJawAa+nZwqSACU0JwhpPnF0AWq9qMKmXX9ryA=,tag:ZwtvFho52ptH3J/ZeIDyOw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaUdURy9mMWw5YkZpYklN
        dnduM1lSUTJvdktZblFMMWREa084TmNDTURJClQzbHNGMlB4dVF4QmU4OGpYQkNF
        cnFkUERrOWRxcy9oMEY2MWNvZmg5UkEKLS0tIHpFbVZ0Mk5HZTEyUnRIdEdRQitS
        TDEvZlNYMnIxbXFNeXE3K0ZpYXV6NWMKd2Ls28QG7XRXCMa3FZGyk3RcTKqXOZAV
        FCLMzE3k5QKwAheV1Z2uWTCMznaxRR14LkZk9ll5cF0y7VW7OysDxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-11T11:37:59Z"
  mac: ENC[AES256_GCM,data:OlJIwCf2Kx/En6D5gc4F7Q7KDjAIgVGHti+vW1tTvPlY298VAS0OtToaWdTu9UK6bZl7ymeOaWetcV+XcybUKIpgptOIVdc2vCpDne3TOSteRkr9w2v4B9t+ojQYNSLgsVwg8eOSe9j1FWIEMHa6ntJ3eSDRoFUiNbe7Ne6/Ptw=,iv:wWwkKylSaZfDsMGjuvR1nfKkmCpAF26VEj0ArTUzjTk=,tag:U4F9+BqUuvZmHd4hW/OHUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
