apiVersion: v1
kind: Secret
metadata:
  name: actual-mcp-secret
stringData:
  ACTUAL_PASSWORD: ENC[AES256_GCM,data:N1oeniqKjOo=,iv:kFOrRVV0rmpqD1BeH/xobAi9uBoYZUc30vuLLrbZTqE=,tag:uFX2xssQ+XlYE1YKyPtucg==,type:str]
  ACTUAL_BUDGET_SYNC_ID: ""
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb1FjcUFnU2grekx0Slcz
        eHd6KzUzQmVzMGphMkpYcFh1bjFhTk00b0FFCjA2U1BiaWpNWGtySzJONzYvV2ZW
        N0VFZ2FnbUg1ME1mQy9nd2VxbHhBNkkKLS0tIE9SV1dLTm02eEpmS3JVYnU4Uk9E
        c2FtRVR5elJYbkc5YyttMFR2V0tmSGcKyS7e/70fTUs6MeoWPGIC3z81boy3iL2T
        M52qDyojezBRSdka98rjkkVJGFYDmdd3/H1CgW7WEiiBU0giHB/aDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-19T13:01:12Z"
  mac: ENC[AES256_GCM,data:jxwnaPpFHky0oBAmrU4u0oms6ndjnItnYBAafhx7Flg1hY0E6fsY5mZzWFbpnnxRHJn2Wz50NyU3A6gWnOnVAqQIqPtDjD3lTRMv1YcmQhm3TDWw/F3UQD/medeGrkTrN/r0dipl+8GSMbKn0Dv2ipKxPlp3BVJ3b+F9LoosZkI=,iv:bTFsOSBFbNABYIuO+oIG/8WsvmUT2ErHs/crfQ2sthk=,tag:KQC6Nkp4YRmrltRLZkPUVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
