# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      open-webui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: 0.9.6
            env:
              ENABLE_OLLAMA_API: "false"
              ENABLE_OPENAI_API: "true"
              OPENAI_API_BASE_URL: http://hermes.llm.svc.cluster.local:8642/v1
              TZ: Europe/Oslo
              WEBUI_URL: https://ai.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: open-webui-secret
            ports:
              - containerPort: &httpPort 8080
                name: http
                protocol: TCP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *httpPort
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
                  initialDelaySeconds: 30
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
    persistence:
      data:
        existingClaim: open-webui
        advancedMounts:
          open-webui:
            app:
              - path: /app/backend/data
    service:
      app:
        ports:
          http:
            port: *httpPort
    route:
      app:
        hostnames:
          - "ai.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *httpPort
