apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secret
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:WX0b9FRCbodsbbQE7I45ZSSJelHNBPlcyUlZfw1LQRGLTTAlGtpVAjIX7UYhiA4C3TwrA/taRGzLu264SI6yqQ==,iv:0tXwdCw36h/P0AR2HwO4oa3YGw1U1hlZdCjspjbEWPI=,tag:PE9Z6k7KMRQQbF/xc799sg==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:LmPdThr3lu3YI6mpFQ3MOv/7Aq0gTYcfAIIHXibiIWMmar7frit1SNgLAxhIZaOHQedGVSIaar16nruSwCqYAw==,iv:ju/+/VG3ZwiZia1NY9SV2vgeGhkOsP3YLb+naxiQk1g=,tag:hUwL7JXCn0EH/vAtKO+eXA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTExwSEFiT0xsZlhHMkQv
        RWk0TzJvWHoxM1FnSUpoMEw2ei9WZHVVWUJBCnV0VnIvTmJra2l6UUlSZGp3WW1G
        VmNjZmJPbU9saXRzOENkWENheERFencKLS0tIE5uUjNyRTM3Y0xHOEJ1YS9Td1lO
        U2Z4SnpVa01GWXZKY29KRFNveHFtNFkKCylAOnC47Nba0ji/v1Z6TvN+qsTAEsb2
        EyIVPrQkGSKarHfkIkiXUveOxToCm6PMlcruey8YZ0YScRxygXsH8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T06:58:28Z"
  mac: ENC[AES256_GCM,data:rL+2NjcpfAlzGuD4CDihF0kk63/Rf90PrDtfL9KWq9gqyqDhn5U5cAI+A7B043LJzMobMyrLyXVzQJeWqak5XPQTgeMCGAt4rMzrVIl4e8fo+www3W+0AiIE+p1npy/CuMhecmYCFQqd4Ox2LY//p9rbOl8htJttNJiWBsLZ9bk=,iv:7HMRA6DxYt/KjD8xPGmxnYjTDe6QqtcFdLHDloyBNZU=,tag:Axy5hprQDTAnZw/uUr8msA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
