# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goboden-public
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      goboden-public:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: registry.system.svc.cluster.local:5000/goboden-public
              tag: main
              digest: "sha256:cc83d96872a1352822112bf10137e11aed3470be04fea4f95e35d161285a8da5" # {"$imagepolicy": "flux-system:goboden-public:digest"}
            env:
              PORT: &port 3000
              API_INTERNAL_URL: http://goboden-api:8080
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["goboden.no", "*.goboden.no"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-goboden
          - name: internal
            namespace: kube-system
            sectionName: https-goboden-wildcard
        rules:
          - backendRefs:
              - identifier: app
                port: *port
