apiVersion: v1
kind: Secret
metadata:
  name: goboden-public-secret
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:t44V+SSeyla3ag4jGJ0pR6NUZD3qquKkSC9tPjo/ZlxAFv5wblob7dqIDRZ/+DEKxUd3UOqNbp+n2xqfviloEXpkoJDwbYMBh12PorI14PIP8zo2eqI=,iv:cohaiuQzRTOm/ISKLW1NmVVpMuTVnXSYSGLtEFFWxRg=,tag:MVJWsp6vmFl3Gzc5ZFZPbA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseitzb2hDUHZ6bDd5eDE2
        a2dFdVNDYUIwUWt6V1g3Qm5wWFU2OWcydUh3CmJtTjEyUjVKTC9VaVdqdi9HYlNo
        aTl6a1hobHBOYmQ1bGdkUUxyVTMrQUUKLS0tIHhGQmVMb0hqWjFJY29uRmhtNkpv
        MWFVR0xxS1VhcG4yeDloanZWMGMrb2cKwCMzci6R3w+ILOoFiP7Wuj+d0dkbVM+t
        sRD2KQ38P2cBpf7JunJ0z0rGK5gnxp7ZpWxV0CnoLrikl7pA4VcnUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T09:33:05Z"
  mac: ENC[AES256_GCM,data:vU2ek8yNcQCFQvp0W4JDS/2NwCfm8RO14mP/BvdGcRRrIVXCqu8oqN87g3FSQ5+P5XefKsGAmFOkNJt2rtS5yDuZSO6wqCZ6fRbpOzeNzzhNTrIBmdKBXtMhtBIwFYNja5ISIY+44SW0regJSKaN/6czsjZNVPRNRtBc59XUXqA=,iv:ps6wmt9/20/cUtSenhPmWd+WiL2STR8BAHzdXRMy8kk=,tag:En1YFcWeciCkTyrogYO5GA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
