# yaml-language-server: $schema=https://schemas.budimanjojo.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
    path: /probe
  targets:
    staticConfig:
      static:
        - 192.168.1.10:2049
