apiVersion: v1
kind: Secret
metadata:
  name: johan-secret
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:5ZyQ4gkTs1MBNkJKzrL0lIyAGImKAZ8gwA17Ctux90KAzn3i3Lr6XSa5jCvkW0cVtxigNDS1XZyuG4RmM0396Q==,iv:KDhRZz6z8YjyjaREgfZ2u97eNV7M2ULwTFNp6rc6e3M=,tag:97CuWsnWzGVlObyxiwWG+w==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:lk/clA==,iv:5ztV2G1n+8uXjJxfINWxtrQJpeL+XdjNhd0csIFujLE=,tag:QJhTm28Euq690GPH7c3AKA==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:q1GVs09AOi9a7tliSYksXC+IuB69o3zj46yssGa5UUqipyG4q6CcYS3KeuXdJ4Z6Jwz+xgZH4JjgIln6KR41jQ==,iv:uDhluk0iIeLd2P8Oo2XlQLEJkhi9D436r/4Gi/jD6ic=,tag:q8+yUnZcrE4K2XBO0xQjjA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdmNkWGczUmFJR3lvUlRP
        OVB2OVhPWTY3ZDgzWmpxT2hGdnUrcnpkWWc0CkFKZ3V6Mm9SYjFjYzR2WXJiaGo4
        QlUxN1R1dTZEQkd4VVpQMkVZNTR5dVUKLS0tIDZaRG12TElyMWtnWTFDdEUwUzJT
        K2U5YWpDaTBHdDJYd0tvZUJpc0ZCMmsKQPSjFPDwEqwrAUbcXLiOawEuMXq/IsAl
        u6IpieHMYG8c5aYNGn+NrXgACjBSsudBUkDz20NZ3b929POF2yISTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-04T20:40:20Z"
  mac: ENC[AES256_GCM,data:HEofonDtZNFxZI/PpTHqbyUzrIbnpLlGERfzl3x3Ayzd+L9rQoKDQsm+/AnM/qgUWA05Zt1q9h0P4jhyxQLmrP83VXvWNxoeaSt47OIs7swttuhIIK1Bs5xa7Ihn9ldZtqu1R7L09GC2s1SynuefyQPnasDG4dQ8Aw2LUlZO5MQ=,iv:fW/M/93Cti1d1ExnUExbcegGsk/JNQJalEG1UTKiwOE=,tag:XrZFQN8dLzGZHDdZf6vwjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
