apiVersion: v1
kind: Secret
metadata:
  name: johan-secret
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:gl4xiK3WKuUxXDzMIRYJjbzwiA6Fv8V5NYCky71ck+1KUDp1sJ9O196aK/mXEQyWyTpceivuwPuTillyeM/aIQ==,iv:jF7YBXhcTuuZvtbx9WLr3upAvQ1RQg+b4h/y7f3A378=,tag:GLQpBRUyouH04lF+pUgYqQ==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM21sMGtCUU5vTm9senRm
        S1FQV3FLWTl1cDhsZW5NR0RPaUNnY2NnbXdFClhPZDlRR1YvaXBhb1JvU04rVE1K
        VFdNT0NHalQ1VjJqdmJreHBPT0pzOUUKLS0tIFlxTGp2SFIvbk9icmVWZ0JMTVZO
        YVRXbi9EQlZkU2JhK204N3AyUmdORkkK9VC3hhNIc91jD8ZHpS4vd0TVNOD3e7Ks
        UyRtDkhqmQ7/pcMcsRAN4Qbk9lisXG3gEAXvp3huxCByr1Cm2lwe0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-19T15:14:38Z"
  mac: ENC[AES256_GCM,data:ciGoNqyInVR0MvkQSSvOx7NLoHeUvEhezK6PcXA4O7rk4e2I4D+uZVaRoOaIxKHRAyXLQwQgChwlmNQVBZkRM/0dIt9G9ffYZYPBTViQliahQBTuXpabbYbIpjwQvrPK9AMiyPKLzpPXIagD+il5uiqfG01VL5BunCMpuKoweFg=,iv:1NgSnHJmsEvTdHLAk7oOngP9ZbW7CnGIwF1YuCOFxJ8=,tag:OpzpYy4LNYLgWNI7F49jYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
