apiVersion: v1
kind: Secret
metadata:
  name: n8n-mcp
stringData:
  AUTH_TOKEN: ENC[AES256_GCM,data:zMkyUtJ1eUsAo/Pu8Wjv2Z7GUFZUUZwGgJe6yLKFOi0l5iEvStBPk/jTElVlAFs1LOuFQLmzLY4HsMsd,iv:MzBs8NW5HqkDJutQsrdgh38ozB45IrUGOVlX8W5zGxo=,tag:WngWo1BoMuRXGGoPIEIowg==,type:str]
  N8N_API_KEY: ENC[AES256_GCM,data:3M/Nx6D2JjFdHQkDPaQJPrRM98tBlEGb43li0GEYX+lyQhhwCD5QmH90R5JW/DRAsA9crubXKmNdZF71aYUvgd3A+oqoc/WLPAGa//OQ0iCPhLpYtaWY0l/4k73Z88pGiSO8pM3CA5bhmKrbPFyVEnmaYmeHDUt+6Ootp/++gKYY9zygTPZ/79RcHIuPjw09ZU5DV8j8m4EJwwKZa306AgCKN0KmKXRRpKyEnOr+3h7Jk460AH+3sgGHgOX03J74A3LgTvssjRRaY7L8b1Mq1TXJRdagfXJZFBrEizObrDWYezfN2WvMjkywukEdHTy/jeDjc6Le76rjBuctlHoHEhcafxjt3urOH35Z,iv:o9Pmj1wVbS6X6k7H7he5nwdEV6Y7yZsn0D7Zsw2Syq0=,tag:edMixLRatTOVF/7BAC5n7A==,type:str]
  MCP_AUTH_TOKEN: ENC[AES256_GCM,data:21sRi/5gyofwsGEYrmQMHyabYuMIaL/hOHWnH5qeSGruLLc0BCvlD/bQHzWQopqbc14h9WEADurCjs8V,iv:WvCgMX9t7iFkJ0m6fTEudWe5LUIzGlTHIxaShdq3iUY=,tag:1PG1QgL2ughAHdHf2mKZ1g==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRm94TGFWaXczcXhUTjZV
        NjdEVFNmM3MyaTFDVzdaK1RkbmNNWWR5cWxJCnpIV2NmSk03WTZKY3EyOFdyRTFQ
        SWx5TEdUSkUzdzFGN09rMHNmWFFNSkEKLS0tIHdLbVI1cFQvWm03RVhpeE5xOWJX
        b28zNUY1WlhRSjVGSzE1aFJzSXhtOFUKgNnTcf/ApN+/FnA/hOzUGyVTQGQYkh7P
        l4kME6gE4DCtYtb5V5KQkLbokVTiiTkjPE0DQfNPd9WkGN1d6QGBBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T20:11:23Z"
  mac: ENC[AES256_GCM,data:LPEA8rqnWnPsGpIWjKyhZHEanUrio7X2jFoCsBAbpeKdpH4Ruj4zVEnfbC0hvJFSv+KX3dneyjlWR1Hviw6SPZFtz8JFXoNc5XzO9h8F0XfKD3W9nhcffAB8nXRs1TPbznqS/qd1LR9Ge/JPdVXKT/8+YjI0rZNIDD0F20fwI7M=,iv:WFsTThS3t+EQKzkbanGZ78XjRC3fnuR9zsVq4u0Dev8=,tag:N2eysc4dWe4T36ebzgYfnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
