apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-adguard
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    domainFilters:
      - ${SECRET_DOMAIN}
    extraArgs:
      - --ignore-ingress-tls-spec
      - --managed-record-types=A
      - --managed-record-types=AAAA
      - --managed-record-types=CNAME
      - --managed-record-types=TXT
      - --managed-record-types=SRV
    fullnameOverride: &name external-dns-adguard
    podAnnotations:
      secret.reloader.stakater.com/reload: adguard-dns-secret
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v9.0.1@sha256:08fc9f649dbab69bc3474b102b0098262ffbd2281509443d10a697dadb1eaa77
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: adguard-dns-secret
                key: ADGUARD_URL
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: adguard-dns-secret
                key: ADGUARD_USER
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: adguard-dns-secret
                key: ADGUARD_PASSWORD
          - name: DRY_RUN
            value: "false"
    registry: txt
    sources:
      - gateway-httproute
      - service
      - crd
    triggerLoopOnEvent: true
    txtOwnerId: default
    txtPrefix: k8s.
    serviceMonitor:
      enabled: true
