# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: adguard-dns-secret
stringData:
  ADGUARD_PASSWORD: ENC[AES256_GCM,data:jiNglmI=,iv:dKcGmt0FL5rrvXg24YoabKqDB4OHjWhiJbg+iQ7TtJc=,tag:m1AuNiQFPxFPpB4NfOmY7w==,type:str]
  ADGUARD_URL: ENC[AES256_GCM,data:KcGF4+/NIZfNo7fxmcr44GoYbcDb8Axu,iv:WrwPMX0kN1YRqwtimmfWtR/EdrHoK/vWV5+WEbDZosE=,tag:NncSfzTM1uaWH7kB93ibnA==,type:str]
  ADGUARD_USER: ENC[AES256_GCM,data:Nu0Y0Ok=,iv:FQUzRwGfGKWRw3pV+bR+snZVrQuMo7SKTJZ7urAvcl4=,tag:hU2emcjCziGpUedOLAWtoQ==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuejIvU2pNeml2cGhMYnM2
        amdGZXNhQ3JXSTlHUnk2MVcvTjNhUlVoalVBClNhYkJycEdKK0ZnYTEwZ2w4a2o5
        UGJjWkdSOXNuZTdaRGovSjl6UVY2VjQKLS0tIFBDNExsRDB3dTRQRGVQaloranl1
        ZGFTbHZiVkVpWHlDelcwczZXY2h5WkUKbivLIfOJ5JlDp9ZA6J2EQaUNez/n0wE5
        dbq7DIDezplNWaLhPYAzxY5wvAhoX5zxUyVjJ5w8/o8IZ2kckQE0Cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-19T17:59:25Z"
  mac: ENC[AES256_GCM,data:Raa/XKpAnyKEMymrnT2qFPfben7JsDlz/Q5aY9GmaN5za2wqwEyJiISkHccw8MQa2hij/wyTDKi6Gnsh1lzOM4LSpLf7oNmfZ5F7FIqea6OTC3uXKnlD2RBYcGu8qLrTWB/bqk2zB2xuYrL1euwIEScpitdn8hJNcppbCPPycR8=,iv:3x0tN+62ZAoYqRxfKZcVD1EB8chHDtHi62hDlGnNNHw=,tag:FKLaRzuz3gDLdde0FiJrmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
