# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goboden
components:
  - ../../components/common
resources:
  - ./postgres/ks.yaml
  - ./goboden-api/ks.yaml
  - ./goboden-public/ks.yaml
  - ./goboden-tenant-admin/ks.yaml
  - ./goboden-platform-admin/ks.yaml
