apiVersion: v1
kind: Secret
metadata:
  name: lubelog-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:AfeDJK8MFA==,iv:GbpC7vf0uTz8OFEUBEz/Ui1bxd4HOVkq+g+CUUBgT/Y=,tag:9xH1rS620CRKrjpGOB2MGw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:NeFeTUI9dNcVUPqp2k9VpnIKUZSEw/sTsxVASl2hws3GUV4v0Cg=,iv:JyJCpba9gn7EbsZux5ZTXadDRUBMMnxCVdkX8pAt4Yw=,tag:9uXyiMw41OjNcRRYL8bwlw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:ik6kuP0mYg==,iv:kye3UlI+mAlQerzRLsG/fL97xjAIF050jQ75eDk3K7U=,tag:v4o5z3d2Nh318eA1V3mBNw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qGEBSBgFMA==,iv:qbnEBMQvFSJtHHWi2mqBZscqPkKFP5rOtHWzVKWLc/M=,tag:qlBewlkXHRH3OUDyvMZfBg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:7pUOLoVwHyk=,iv:JnMpu0udC1fMqx+6ch1VQPY2o37wW7rxQLTXAdJH/Bo=,tag:SDTH1d3RGFC/eFAHSDSlEg==,type:str]
  POSTGRES_CONNECTION: ENC[AES256_GCM,data:SwprxB11TgAQ2nw+Dcm1QhJrn3totrky3pHvZt90Fry+GeIdp18SsMbCCmzBPMpPSVtAHTNj4wqVzTx1w5w8jRDpKXkN/lcXr7KFd8C1ymFztoJwr9X2Bge0gwSMQCohsx5MHTIldaXAteM=,iv:4vZaRTNOrA9VmNP7UXHMo0q+WMk95osYmDhCqKfOUAE=,tag:LXdVBsBqlx72UJD1vRYaPQ==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV0NvMlE1Zzc4TmZ0bThU
        aFd2cEdKOVY4R0NZTDB3RWZUeCtuTThsaFVnCnVjWDljeEs4RWRQaGtuNVFQandW
        bDUvcHh3NUdtNjAyc3IzbnJFbnM2SEEKLS0tIGxJall2cFJGY2kzN3QyazBaQnBT
        bDJnenVuWktHZGZEVHExTXYzQU9lTzQKCy00Lkp2EeoFs8GoZk2A33coAX/VRSj/
        P30OluYUkeiqiDCRCU9imB+OlJytrzwG/KvaRnaPiWtzfjALK74q3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T12:49:23Z"
  mac: ENC[AES256_GCM,data:3gIye8j1o8c5ECOywug7d6ScdVNN/roA8i7MhwGhzR+7/+QLjo+FKHKkgTnARAIECMav3Z1exauBgEa2GrpD6I+QQGDvJrHJ3Lqm35QhJqnyDQnz+Sof9ivDRejxkM4D2rZeaRzKfWM/dC/jlu/w9EoX4lDwdhUR5EqP+efMmmI=,iv:tZ8ZYGa9gonssWc4BFY+atxJXueIVin3GNCVKmuAYWY=,tag:eQEMiYP46mKIFxUu50p14Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
