apiVersion: v1
kind: Secret
metadata:
  name: arr-mcp-secret
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:e1lqqqUYg6PANuA3kivDO4V7wTMUUi0nD3mbDWl7nik=,iv:nUPanodqJTnAC+XRc6GK8Yy7vYsAk4+Ls33xuitInZ4=,tag:HHBD17+xw06/U5obL09tPw==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:XsMrN273vsP8s31TzOW6RSljFQ/fKrqLqkaJohBhR50=,iv:amaMLXCm5c2GDP+vcsbO3p1vur0moG9rnm1e+WMg/1Q=,tag:h6JN/yZSgQsq+0gcIaS7qg==,type:str]
  LIDARR_API_KEY: ENC[AES256_GCM,data:L7YZlsD5ENsvP64/cpwwVmcQkv0VNToz8M4U/TJ/4nY=,iv:Pm9uq2u8Wt7b/1oPrjz5B/66cwPlNJgU31Y2gnQdAjw=,tag:entkz95uDpuB+WEMEAR+2g==,type:str]
  PROWLARR_API_KEY: ENC[AES256_GCM,data:JNXy6jgw//6Z6h2UFkDkchjUE9KH2LWK2kFh5jDbtmI=,iv:nLDz/MZuDGp8ZD+K/aX3WqZD43MXYvgIbY125ZSZlHk=,tag:UscRN77Y7UeQAvPQx+FVhA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONFlUeTBLdkNtVUhSQmQz
        YVU2ZzFhU09rN1JNc01jRnlvRVhNTlZTcTBVCjhudlVUOHlNTEs4OG5BZ3FteTE0
        ejlhMkRRN1FYTnloNHFEcHdSdXpnYWcKLS0tIHZQZFI4ZHlDcjNYemJ4cllZSmVq
        dFlsRjNlQ0RDRUM0ekQ2elhtQlh0cEkK4QaKdVy2lvNbxTLRw5YQNg+3/eKKWbJr
        XdauUxJmGNWIentCz4gT1b3pW094ULcj23aLsRiMpFZ8GSUWNHgd+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-19T19:38:54Z"
  mac: ENC[AES256_GCM,data:aMMgERshB8d41xu4wkOYp/53BnktYRdkglQ6ECDG7yCNvH4Xnq4enrK/dKV43KUe9kGnbFP7/+7wD7AY1AOKfoWU6HYG8RHCAivhV6zlBfRryO05uj7JpLC1wqGTvbx4MR8r0YoPa1P/RrNZT4Q3VutPGx4wimEwzrtsuToAiwE=,iv:Y+UbQa0LRK60k1Sx7oMGyN08nFiiNX8FdYLWzU2hlIo=,tag:HTOMksvNR9WcoelLkqFD4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
