# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BuFyw8PYqADnqdO8jmpw2n67Kt1lGbFfsFFiS1j90MAou6uHNS29HQ==,iv:BDiyiexv4hSUgGqgkcHyU9qiVRN0b6QBS74Tsz7FIW0=,tag:F1bEPpdoCHEbzAniAZu7hA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbWlOM3BzSUptVTNOOHE4
        SWlIWEREWmorNVJxK0NFcDlVVGhoSVpLRUd3Cm5GM29QMXR6K0czalZaRmhPS3E0
        Z3h5amhRQ1pnU0MybWtXZWpRSC9HdmcKLS0tIENzaEpublpTYWdlaXVjcEZzbXYr
        RzU3ZWd5NUZRNjJmQytSQWN1TVN6NWsKxKkqkeiIYVoZQOvx1ldte48EX3kkDdML
        yaJywlNgzZPNGj1h/QXx3mZd4CBAA+ABnYzVE+YA98QFpPnKCkbAqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T09:40:07Z"
  mac: ENC[AES256_GCM,data:wDljc98d2Urq3y3xbZ5jvfFY+0SrM0/udFHGoIYNROErPmi/GpTesIzpdVWFFDyCI8G/2iBQ+JIJkolUjxsIi9Vv8DHoNaRfP09dFvN6kfAAtATVDsrWjPNjSOxN5cbWoqsOkVSwCT6a4RebXbr++E1twYk+i3H4SWS2MTSOvVM=,iv:+/Teag3MNHHJGBb8q/X6woiFwD0tU2wyw8b0jlz8r7I=,tag:TmIFGXt9m0RdnjwHQC3wUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
