apiVersion: v1
kind: Secret
metadata:
  name: camofox-browser-secret
stringData:
  CAMOFOX_API_KEY: ENC[AES256_GCM,data:XMK0g0Bv/L59galZGXUrZIwHH1BKRJIoBeEbI6nTDM5T1rEgYTbuphVYC4o=,iv:ZTp9yp2a/n5RSNgiixcx515K8YxlQLbLQVJUk5XE2Cg=,tag:iUdmL1Hi2iep10BukTl0Ag==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaTRxbFE4UWFzQ2dMalBE
        VTZaYjhvUm9ZVjhzc1Y4VTcxU2tzK2V4N2wwCnJ2Mkl5cWFTdTY3cTJZQ1VLckJ1
        VVRLWVMzbE9uYkM1aXZVNzNOZ0tIWEkKLS0tIE9XeFE4b0hVVjEwekxXZU1iNWxh
        aXh3aGJPalYxSkdRMkZyMmd1bEc1a3MKXI61AoYTQpvW2Fy6ngbZ9yp9Dnq9r3xC
        /8WvVKbElX9m15S+7U+y+euLfokWihMdqpzYCJEJXnEwAHPLza1X9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-30T19:26:19Z"
  mac: ENC[AES256_GCM,data:rMOSdvzDebMGT/dD9ELIdG2qXjmBMhDsVElrWGF+2oJMKwMScYw/nopnseCRBcPMdU57CNI4mLMOV+TxPpZT3wflYS9BPuyQFlIADLsI4c7hu5UKhe8BHfUqY3ND1INcb1avNTqBcb0VG+gpV3JBfY/fNX9Z578/7/c/SsE9Kqc=,iv:nJYMPrw+mnaIA8zIop4vyxrmaO6JYTDUjH9UdTifx7Y=,tag:iJRKvLqSA54D7v0hgC0a0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
