apiVersion: v1
kind: Secret
metadata:
  name: paperless
stringData:
  #ENC[AES256_GCM,data:y9H8XeLZHiY=,iv:uHg+b3eT3FnH2+ytja2phhTUyjztGqmU9Cm6AFNITk4=,tag:5utwuplXsOgaaAsb9zRSPw==,type:comment]
  SECRET_KEY: ENC[AES256_GCM,data:OMnd3I7xpA5AiIvjcJYF+DKN/F5D+gjMX6ECD7S/VUKax0/qPi6btLLvGbt4NkTig0Q=,iv:ImHy4gJadhHk/Bsk2k5Ub5kT/P0I4EsAIlstItnWpak=,tag:hzS0MErzlPIFlUfJiRkH1w==,type:str]
  PAPERLESS_DBNAME: ENC[AES256_GCM,data:ahQRDI7D5Tcu,iv:NTHr25G73KrA1BE4i6isQhK5yNeZnSRVQEQZzjGML7o=,tag:HdI7aHOJf1aA/xpz55xoVw==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:ukmibaMxWGaW,iv:NqT4S6SwRnSttZxkFCHMUupiQZ8PA6eTesz5NSnEh9c=,tag:3A6jseNALerQp4XcJtCOAQ==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:d/boCepguhNY,iv:NxAdnkbapnZ+Moyb8p5O8pUVfE/33X0ReLlOBK8lb7Y=,tag:FWibky6m8YdQb8RLYULU4Q==,type:str]
  PAPERLESS_DBHOST: ENC[AES256_GCM,data:R7u0O87v6nZJY7Cgy30jMs6YyJ8OcEAVvB3IIgDuKcDe8FKi8Po=,iv:WM5AGVlrRBckzXn3BdFY6w+wng1NcjrRCxsawRMW3oU=,tag:GaCwO2zeLzMUuz95KRq6+Q==,type:str]
  #ENC[AES256_GCM,data:0n3TmsaLWPSxmPeJue0=,iv:EIeSQ2/DYl0fnMaXTKl8LmgycZWzTk7AkbxrpF3pa98=,tag:DWe8L48JgSbUqklB/9OmJQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:JTUM3nbrfd0L,iv:6kWENhHyCluXt79xIVMmxLLjrNAigH8zTQUKPitgrbI=,tag:2qprLtq2JcLiBlNwB6KR+w==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8cJLpiYHphjAImLex86eAUG/OOY+juS4RnBfHrtoVeE2KiIZskg=,iv:eX0oZA00EgeycgctLdzT/3umr2Ix4pRYtbnVXtJwcEE=,tag:VgaFsFXORFRmGa/SnGrYFw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:M5x6vsgKDpTD,iv:YpmAjy6Xv3rxjukLpN14DaaM/k+pqtMB8uBq9IOHrNo=,tag:KCoa1IXo9j+6CWwwh47RbQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:8lhkQwArR9Km,iv:aL8yvafgNdPTybQ1V59jiOeTfL9ok6qEjnsmxwHr8So=,tag:TOJnyhykqHdGmT8auXsSfg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:l6s3h6c5M/c=,iv:hnOT7KhDci3WONJhKMM7ffODg1UVjSqjhCitCquAbyQ=,tag:YM5LkSgJbNCrIDDWuKmevQ==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNkZIWitYWWoxNlY5ZnY1
        QlVqazBHSzhkNXpRVGZJMllSaEExWUFJcWwwCkFodlFGa05vbW9vVit6UFdsVzIy
        Y25GeDBrU2tLYnRJZ3dveXRmdHBHN0kKLS0tIGoxYVR5UitZYTQzdE1VVi9uajNq
        TGZKSDhKZXZWK1NGQlVFekZKendzTUEK307YBmmBHqb1T5N8qOWJjvJnsPAmyjXg
        K8mrmgfGdARpi3CVPi8pvK1cDQxViHYPhY/Osr/8GOcGPoK0N2R/nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T18:54:44Z"
  mac: ENC[AES256_GCM,data:SAmZBQYhq8K68Dd/kpAhNQSU5fkEhfYKHOT+LjJMw6DZeiWFS4zx6sO0x/6myCbrBf9FRT5EjODey82vkGc8RtdMMdsa1QrHsfZedMrJHoXtNVzhq7WbMZDHzOQ4h2MgwqwhqvS0n/EPVwBOg3uf58PKvMBev9ktWfLNiEuKYtE=,iv:eBIqT+MbIuuQDDBcDmlZI+xqSbr+5LwSYjLzp9/BbuY=,tag:ROthE0sPgs1mZ3TApjgoVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
