apiVersion: v1
kind: Secret
metadata:
  name: goboden-postgres-secret
type: Opaque
stringData:
  postgresPassword: ENC[AES256_GCM,data:sCwX8qa7ajc=,iv:njFfmXBKCNp52sx83E9y8HI12/lMWii0425PMhlNWjE=,tag:Vhp6bVJEN4cqXHZTvTfYWw==,type:str]
  userPassword: ENC[AES256_GCM,data:ZWKaO8wKYsQ=,iv:vE31epMzRSfx3cZh+qahNLaBhtp1jlTa0W27yRFOrik=,tag:CtE+FnaQ1R8/JPKPKLBF9A==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUUFuOVdVYXBOV0VCVGxN
        bkYvREJQYnIrczJmSDZYYkh3RlRFL0dlejJJCm1XUXFFRmdkcmFXU1ZXS3lIRUVt
        L1V4TEdLSWFMbXZ5d01iUFg3TzAzVkUKLS0tIGVSN1kzeXByaXowQ3BhL05XOXFu
        eXowVWtCWFExSjcxS3YyYmttM21jV3MKi4Zayu2MKd0G7MR6dOveV44PPhMPbI/r
        k6WBmfF3F4RVdp0+cxNXAMIEFslMpRja3Urr2tRmVRkUkvIdACDQQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T18:36:43Z"
  mac: ENC[AES256_GCM,data:TMkBZ0ktwPz55QRXReanYPrJMNVBmGRusFPOv17FhakVm1qe4OXcyGLjSExgaqHSzRnZGVDVS59kE6hmxXiPt1X2y+GkPZGUKHDIh8TW5bNdm4XJEBwW2ptq2TNgnTKRnqNoN3PWXhdmWxq/QWOMc4ga8SgOI5pKZDvMPsjwCkY=,iv:QSy/U22I+jGAud7I3+qyvzS5CLYw0qU1d9NvzZBkMYc=,tag:EjKoq6KjduT+G6WcnUtuxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
