# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rediscluster-ot-standalone
  namespace: &namespace database
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: ot-standalone
  path: ./kubernetes/apps/database/redisclusters/ot-standalone
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: ot-operator
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  targetNamespace: *namespace
