apiVersion: v1
kind: Secret
metadata:
  name: hermes-secret
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:P8Ph2FrvpIXXFqcapExx4hJCEQ5X79hOvgI4KrJm0UVcAAeN+CT608VY5VAAOVsaIowCoYfGAAK2LmQY6/PcLA==,iv:mm0yBLS/fLDtGfLQtClYeP+G5LP+DgBQHuMSKZXBQu0=,tag:o8+ckBVusW9ZiWdCVHpRPw==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:QcsO/w==,iv:AwUbh7HU3egPcWXp597xPLea/y6fGmLh6vQin9E69qY=,tag:UyUKkH9NQNklRpkg9OpmDA==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:u8tKF/O/gVzkglp4S8kZjvFxh9HbsyTWIgBmPrmUChfb7GKnWBxg0tRH6g9sv9nHQIKlgSwRYJZQNKyEVI00yw==,iv:i9OEnPTB+0SWIs6kJkIisMX8pL0Zd5VtII2IFk1BOuc=,tag:3xAIkQqniAlXSDS8RuL3Gw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeG45eHU0b00xSllhNEFa
        eFBMa2cxQWFIdFFSbWt1OFg4N0xhb21SOURrCmcwQUVxL3RsRFhGOVlncTJwK2Z5
        Q3BKNUVwemM0MUxtU1Qwei9tUkxhK1EKLS0tIEN4MllwaENKajRiZVowSTRTNmo5
        ZjNEUHlCbFNyYlMrN0JFbTRTWEY4alkKhFN6hKWqYkOuWsSXhCrSOab2vNI8BUbr
        zLhvf2mOZLsAUe7Za2D73QXWgjITUlgjMsQvGhSFoGx4hUP9tQ/u+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-04T20:40:20Z"
  mac: ENC[AES256_GCM,data:YU3X8qPmTt6bdqFqgTxF+8s6X+T/2XWoq5RBu3St53pByH7DPK4YiPDDM1sRAgUw3hBDbR+BCj/Brvh9uM5rqZpzYhAjkPdQeg1h74C/EfhzPFf83OXaMWRkO61RHCSjB/rNp1JciaranLXrP5qpjbIgeaHi4g98WvecDxuK2O0=,iv:JDKfKeWk9RJrbC63LvimZJvxcEr3T8s2ls0EV3J56Nk=,tag:6m9DxcURtBho0INaYbtxhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
