apiVersion: v1
kind: Secret
metadata:
  name: hermes-secret
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:C/PnUT3u5E1iN12kqz51n65p7NfG9mhVqGsy9jvd0M24x3wMadCZI87Q5iskdNtkQzchzV0ap0uy+IoVxMln0Q==,iv:GAWt2pEcwwoK+Ljf47je9XnpLdSXnsClEq36xgtTTH8=,tag:wpQOdlCM+4BmqhJyz3mmfw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUCtqcHUyeFJEQnB4SzBS
        eDVkMnRNbml3U1lySjFnM0Y0RXlydUlSWEZBCmxZdlhWekJXekRSVUg2dS9iSVh5
        V09heUVYNm1BRTM2TmVCbUlsclhLT28KLS0tIFdtY2ZCRm4rNWowWXdab2ZzVU8w
        cXZKMWpjdGtZY2VMVnNBYVdHdlBWSjQKdBK40pndrDpUI+ihA1hc0X9D0I5wXphp
        1O476DS5Q0PazyHRXmTE76+KSEvg93gvmgGOAytOL64BwGqx8gdJxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T06:48:20Z"
  mac: ENC[AES256_GCM,data:XAoj2GMUD7INWn0WLy/Zi/q96Pp9aPVH1hyyWBH83VPCc3fDEoc13bOLftPH+hqoSGFsmg+CXS3MIPsr5qkGwcDL08DU2OXzvYnVy6mEE9w9Yv3H+pWW1wVrf2+RBBl7yjvM2uK0IsUlmTtdLT74uIORStFzft+Iek4v0C6gweE=,iv:PKKWoU3C6hq8MOobTDYhQtlSlTgDgaDI0JUsuW45OzA=,tag:zmtbkx7dGWj6Cy2/1c3ufA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
