# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app makkapakka
  namespace: &namespace llm
spec:
  targetNamespace: *namespace
  path: "./kubernetes/apps/llm/makkapakka/app"
  components:
    - ../../../../components/volsync
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: makkapakka
      namespace: llm
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
