apiVersion: v1
kind: Secret
metadata:
  # rook-ceph expects this name
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:FxRhKsxQN8sv,iv:siGjHc8u57vnIy+iEarYLVRjmGt/D8O0acfkFT5zbqg=,tag:INeeYoMa285fSnU/UfmfgA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UkkwbVNmb0pLVVZHRXlF
        b0pwR01GbFBhWEJMcEY2bElwUWJFbEp6dWt3Cm1rcVkvNjlmdURRRlVpTHVXWk9Z
        c1V6YmtDaXZhbjhsSGQ5MnhRVlVrSEEKLS0tIC9xcSswRWJnejNZS1loSEFEQk9i
        NlRlTXhLbTF2SGt0MExxZVREbFlkTEUKWjKsqb1dU5kLdTI4WJqMy+sRQHD6ypE7
        Szdb0XfoDWzRNmgQ9b7IpYRKQHANGhD2jC0kCI9ptnILScwhNSrTpQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T12:04:12Z"
  mac: ENC[AES256_GCM,data:WXesBx9lywcH712wQD3OLbDhwXlaedUiDT7BA1PIZ1dNdtw+On+TGYBX8goySSWysdT6INwO7bSueUB3rE3xJga6TJUcS9/I/6rkltP2T5jFUT1OpWCoQOWuWITPUxwr1IMn+OVzSy0mxaLxhMjbUOrzcuzf+CITaXiSiYTq4jo=,iv:KqRuJTdqtsVfyS0DSA/q1/0WGNrgcl1vponyz/UKIS0=,tag:3UqTafYYnRc088G3Fp8zYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
