apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vs0aGswp3gfyQHQ=,iv:IZp5aofrnb6tDFZzF7GpExQ24p8t8yXFqG+xKvxJDn4=,tag:bcGHrbZ2XuwJXxywfZwhtA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZlFXaGRpeXkwN1k5SVNa
        eUhCbXNrTzliUnVhc29aUmc1Nmg4cFRUclhjCnRYZkxlcGxPbTlza0dWS3IwQ0FI
        cWNwcVU3VkNPTGNLZFUwUmFWb2xjMGcKLS0tIHkxU3BlNWtsZ0tIdmNpR1Q0WEJu
        c2R4bDV0N3NRTm5sUHBucGhNTDZJaVEKgd0NCXAKclA57Sm7xBuMxYGL1HjCRSXw
        +FpJbsiia3SXsb3V6c/GiGdEqNl0P+9X16wWbY1+8w85RZNGRPJ7Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T09:40:06Z"
  mac: ENC[AES256_GCM,data:Yz/CCTBaLChtwJPrRu0fK24iLkgABgB2PoT29ge4/WOSxxsOR+67eHks7gEVsrgqPJrcIXeJthAPs+lk0C8KuBrcqc1laWTXCCD+9uXoD9hHoufbbBeGTQqJ0lGz+RolIC4hGM/kfjfliQvXeFY2O6sd8wAYisuQkT6GEmncpZ8=,iv:hU1AW3zdpGGGlvXYZQS2E5oBYdbpwPQfmFpt6xoQfF0=,tag:VPbEui9xwGu7nQPMWDWPbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
