# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goboden-api
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      goboden-api:
        strategy: RollingUpdate
        initContainers:
          migrate:
            image:
              repository: registry.system.svc.cluster.local:5000/goboden-api
              tag: main
              digest: "sha256:bb42bd201136a5598f78acd1af4fb5a8c6bf877c5c4d4b13fdd518bc0f0988fc" # {"$imagepolicy": "flux-system:goboden-api:digest"}
            command: [pnpm]
            args: ['db:migrate']
            envFrom:
              - secretRef:
                  name: goboden-api-secret
        containers:
          app:
            image:
              repository: registry.system.svc.cluster.local:5000/goboden-api
              tag: main
              digest: "sha256:bb42bd201136a5598f78acd1af4fb5a8c6bf877c5c4d4b13fdd518bc0f0988fc" # {"$imagepolicy": "flux-system:goboden-api:digest"}
            env:
              PORT: &port 8080
              BETTER_AUTH_URL: https://api.goboden.no
              API_CORS_ALLOWED_ORIGINS: https://goboden.no,https://platform.goboden.no,https://app.goboden.no
            envFrom:
              - secretRef:
                  name: goboden-api-secret
            ports:
              - name: http
                containerPort: *port
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["api.goboden.no"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-goboden-wildcard
        rules:
          - backendRefs:
              - identifier: app
                port: *port
