# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goboden-api
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      goboden-api:
        strategy: RollingUpdate
        initContainers:
          kratos-seed:
            image:
              repository: registry.system.svc.cluster.local:5000/goboden-api
              tag: main
              digest: "sha256:8530cfd3998db5eadb1281c0e53fe516f296c81cc8735fc3dc68b7d563fc92b6" # {"$imagepolicy": "flux-system:goboden-api:digest"}
            command: [kratos-dev-users, seed]
            env:
              KRATOS_ADMIN_URL: http://goboden-kratos:4434
        containers:
          app:
            image:
              repository: registry.system.svc.cluster.local:5000/goboden-api
              tag: main
              digest: "sha256:8530cfd3998db5eadb1281c0e53fe516f296c81cc8735fc3dc68b7d563fc92b6" # {"$imagepolicy": "flux-system:goboden-api:digest"}
            env:
              API_LISTEN_ADDR: :8080
              KRATOS_PUBLIC_URL: http://goboden-kratos:4433
              API_CORS_ALLOWED_ORIGINS: https://goboden.no,https://platform.goboden.no
            envFrom:
              - secretRef:
                  name: goboden-api-secret
            ports:
              - name: http
                containerPort: &port 8080
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["api.goboden.no"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-goboden-wildcard
        rules:
          - backendRefs:
              - identifier: app
                port: *port
