apiVersion: v1
kind: Secret
metadata:
  name: goboden-api-secret
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:8Sjc35UyZXnvuHUaCM+EcaTEiJa2jKbzw1m/eoW21LAu6hCgBsmtpG8T0Nz2QBEwdlwvRoP70G981k78uMY3Qs+++deSFSC0k7jzp3atcxM41VRSzAA=,iv:gjcgclmmWY/YoYDH8kLRjYJUYvgf+jeyCzlcq+6NWn0=,tag:SmkjyfZbxpBIc2sVTn1dIQ==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZ0ZCd2gxMVE5bUNldndz
        UlYweXduZWpGTWVpQWxIWGl4VGFnLzV6R21NCnVHdld0OGZySW9vV3dTVHpGT0lL
        UGU1UHVoOUkvVG0vSGJQZTNBMVpJUGMKLS0tIEtSZDk3a3UwaGJHY0llNWkzNGh3
        aC9MOFp0RUN4eGdNWVlJbmhZMm9aK1kKUMhhjO+lCOh9DkLQAFWtQsGdn87+bu5E
        zNbvy2lArES+BrsbS/vJHMYQt6tU/eHVf2bKoVG69xc6EtPtOViiZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T09:34:23Z"
  mac: ENC[AES256_GCM,data:haxGLm2NZJvVFTNIx1ZHX5+4+RwkXfS9u60i/l15aPNkKzCQHENxnE2wVjaIW23gWK7Tu8acP0nJhIELaYMLpRIM4nrW7LYaM6EDcAqa6uO7Pf86LdpD1fkr7OaAne6z1GU1E6VHyaDCHu8vwyUUhBGTOm6PZ47PS7q99pt+Cjs=,iv:8DMl7V12lMRyVhc//zuOoFhCHt8WaGkhCC6v2MkoJwg=,tag:IRI3yttIWHAzHNLGcpXcKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
