apiVersion: v1
kind: Secret
metadata:
  name: goboden-api-secret
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:anuvUI/zjFjrGh21NM/DukewwZF0D2UWQ94PXjH3UNht0BEvbQAmKFgL6UJSgXuiopnsFO/9//P/L//CRHhJW0Jp2m4pEadKMrshfBUVfeqE+cQE3cA=,iv:bN3dSWOWn2XcOj3BzlwI0Qe+V+C++K9DHxHJKpK1Qk8=,tag:+oa9cKX8qvMztLRqM0Pe9w==,type:str]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:dwatb03vOOIB/QfHBz9iW9oTyYfmip5ScrpzaNRARFxrIaah3eKxOuPdbdQ=,iv:YQKJQkgAyL5CbTbpHv4ldMLaw0GcObpCuMSbIkAl7YQ=,tag:ERTaRtE1/9Ho3oejtZBokA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVUt4S3FZdHMrVjMzUTZK
        bEJNYU5nU1pXZVVreS9KVGVqckdQMjdvNmx3ClNMd3dsb0M1WmNwMXhBT0FSODFn
        bFRqVWVGVzR3U29uaHdpUE1MS2o5MncKLS0tIGJrampOQ3Q4K3A2KzJEZEgvcjE5
        M0pWTC9EVnFta29wblpSdDZDOWxiT00K8kY0piIERbJjOTVSRKo1APQF/Q2MuUE+
        6t5bk9n0v9suvsI/IFywvQj3qZ5BW8FZlFtzUWSxfjTfabEfg9CgrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T08:36:53Z"
  mac: ENC[AES256_GCM,data:QPuaB/ZPqP8DLLiqKz0eYYbQUhhVKPs7uabb+3r0C6BIblrXkYtxEH4y3xXz4dBgLI/D21za41AScupncuViykl2kUN0wNLwt1A7jLgE/e5R6ufZKk4Z0YNGsyJDRvBIUi35iEXZ/CBVwFqm2Wq/HtJH2RJXxfpN81GA4BJ0UqU=,iv:0QgFqWYZWXvPl3CrnUaWZ5LNJFyzRvIghMAdMCdZwM4=,tag:CKR8bCaTGY25Ed5UvackAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
