# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tailscale-operator
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    oauthSecretVolume:
      secret:
        secretName: &secret tailscale-operator
    operatorConfig:
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret
